name: reinvent
channels:
- OpenEye/label/dev
- rdkit
- soumith
- conda-forge
- openeye
- deepchem
- defaults
dependencies:
- openeye-toolkits=2017.10.1=py36_0
- backports=1.0=py36_1
- backports.functools_lru_cache=1.4=py36_1
- cairo=1.14.6=5
- fontconfig=2.12.1=5
- freetype=2.7=2
- gettext=0.19.7=1
- glib=2.51.4=0
- icu=58.2=0
- ipython=6.2.1=py36_0
- ipywidgets=7.0.5=py36_0
- jupyter_contrib_core=0.3.3=py36_0
- jupyter_contrib_nbextensions=0.3.3=py36_0
- jupyter_highlight_selected_word=0.1.0=py36_0
- jupyter_latex_envs=1.4.0=py36_1
- jupyter_nbextensions_configurator=0.2.8=py36_0
- jupyterlab=0.29.2=py36_0
- jupyterlab_launcher=0.5.5=py36_0
- libxslt=1.1.32=0
- lxml=4.1.1=py36_0
- matplotlib=2.1.0=py36_1
- pandoc=2.0.3=0
- pillow=4.3.0=py36_1
- qt=5.6.2=6
- webencodings=0.5=py36_0
- bkcharts=0.2=py36_0
- bleach=1.5.0=py36_0
- bokeh=0.12.7=py36_0
- bzip2=1.0.6=3
- certifi=2016.2.28=py36_0
- cffi=1.10.0=py36_0
- cudatoolkit=8.0=3
- cudnn=6.0.21=cuda8.0_0
- cycler=0.10.0=py36_0
- dbus=1.10.20=0
- decorator=4.1.2=py36_0
- entrypoints=0.2.3=py36_0
- expat=2.1.0=0
- gmp=6.1.0=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- html5lib=0.9999999=py36_0
- ipykernel=4.6.1=py36_0
- ipython_genutils=0.2.0=py36_0
- jbig=2.1=0
- jedi=0.10.2=py36_2
- jinja2=2.9.6=py36_0
- jpeg=9b=0
- jsonschema=2.6.0=py36_0
- jupyter_client=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.30=1
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libxcb=1.12=1
- libxml2=2.9.4=0
- markupsafe=1.0=py36_0
- mistune=0.7.4=py36_0
- mkl=2017.0.3=0
- nbconvert=5.2.1=py36_0
- nbformat=4.4.0=py36_0
- nccl=1.3.4=cuda8.0_1
- notebook=5.0.0=py36_0
- numpy=1.13.1=py36_0
- olefile=0.44=py36_0
- openssl=1.0.2l=0
- pandas=0.20.3=py36_0
- pandocfilters=1.4.2=py36_0
- path.py=10.3.1=py36_0
- pcre=8.39=1
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- pixman=0.34.0=0
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.5.2=py36_0
- py=1.4.34=py36_0
- pycparser=2.18=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- pytest=3.2.1=py36_0
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pyyaml=3.12=py36_0
- pyzmq=16.0.2=py36_0
- readline=6.2=2
- requests=2.14.2=py36_0
- scikit-learn=0.19.0=np113py36_0
- scipy=0.19.1=np113py36_0
- setuptools=36.4.0=py36_1
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- terminado=0.6=py36_0
- testpath=0.3.1=py36_0
- tk=8.5.18=0
- tornado=4.5.2=py36_0
- tqdm=4.15.0=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=3.0.2=py36_0
- xz=5.2.3=0
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.11=0
- boost=1.63.0=py36_1
- rdkit=2017.09.1=py36_1
- cuda80=1.0=0
- pytorch=0.2.0=py36h53baedd_4cu80
- torchvision=0.1.9=py36h7584368_1
- deepchem=1.3.1
- pip:
  - backports.functools-lru-cache==1.4
  - idisplay==0.1.2
  - ipython-genutils==0.2.0
  - jupyter==1.0.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-contrib-core==0.3.3
  - jupyter-contrib-nbextensions==0.3.3
  - jupyter-core==4.3.0
  - jupyter-highlight-selected-word==0.1.0
  - jupyter-latex-envs==1.4.0
  - jupyter-nbextensions-configurator==0.2.8
  - jupyterlab-launcher==0.5.5
  - openeye-toolkits-python3-linux-x64==2017.10.1
  - prompt-toolkit==1.0.15
  - py3dmol==0.7.0
  - python-hostlist==1.14
  - qtconsole==4.3.1
  - torch==0.2.0.post4

